### ISSUE TITLE
should use with the "Operator Mono Typeface"?

### ISSUE THREAD

**Issue by IAIAE** [ceckenrode/vscode-chester-atom#1]
your's
![](http://p1.bqimg.com/567571/d18dc809571e6fb8.png)

mine
![](http://p1.bqimg.com/567571/6323bcedaebdff07.png)

should I set ?
`"editor.fontFamily": "'Operator Mono Typeface', Monaco, 'Courier New', monospace"`

but it doesn't work~~~

**Comment by ceckenrode** [comment]
Just the "Operator Mono" typeface. @IAIAE http://www.typography.com/blog/introducing-operator

It's a paid font, but how you obtain it is up to you
